site_name: MSFabricUtils
site_description: A DuckDB connection wrapper for Microsoft Fabric Lakehouses
repo_url: https://github.com/mrjsj/msfabricutils
repo_name: mrjsj/msfabricutils

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  navigation_depth: 3
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_toc_entry: true
            docstring_style: google
            show_source: false
            show_root_heading: false
            filters: ["!^_", "^__init__$"]
            show_object_full_path: false
            heading_level: 1
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            docstring_section_style: table

nav:
  - Home:
    - index.md
  - Usage:
    - usage/installation.md
    - usage/etl.md
    - usage/fabric-api.md
  - API Reference:
    - Common:
      - common/fabric-duckdb-connection.md
      - common/utilities.md
    - Core:
      - core/authentication.md
      - core/fabric-api.md
    - ETL:
      - etl/index.md
      - etl/sources.md
      - etl/transforms.md
      - etl/sinks.md

# Formatting options
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ['.','docs/source/src/']
      check_paths: true
      dedent_subsections: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true