name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        dependency-set: ['fabric', 'latest']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        if [ "${{ matrix.dependency-set }}" = "fabric" ]; then
          echo "Installing fabric dependencies..."
          pip install \
            polars==1.6.0 \
            deltalake==0.18.2 \
            duckdb==1.2.0 \
            azure-identity==1.17.1 \
            pyarrow==17.0.0 \
            sqlglot==25.18.0
          pip install -e .[dev]
        else
          echo "Installing latest dependencies..."
          pip install -e .[dev]
        fi

    - name: Run lint
      run: |
        ruff check
        
    - name: Run tests
      run: |
        pytest -s -vvvv tests