name: docs

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
      - run: mkdocs gh-deploy --force